version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - mkdir package
      - pip install -r requirements.txt -t package
      - cp genai_code_reviewer_lambda.py package/

  build:
    commands:
      - cd package
      - zip -r ../function.zip .

artifacts:
  files:
    - function.zip
