version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo Zipping Lambda package...
      - zip -r lambda_package.zip .

artifacts:
  files:
    - lambda_package.zip

post_build:
  commands:
    - echo Deploying to Lambda...
    - aws lambda update-function-code \
        --function-name GenAICodeReviewer \
        --zip-file fileb://lambda_package.zip
