version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt -t backend/

  build:
    commands:
      - cd backend
      - zip -r ../function.zip .

  post_build:
    commands:
      - aws lambda update-function-code \
          --region ap-south-1 \
          --function-name GenAICodeReviewer \
          --zip-file fileb://function.zip

artifacts:
  files:
    - function.zip
